# Generated by Django 5.1.4 on 2024-12-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_worker_nss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nss',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='nss',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='place_of_birth',
        ),
        migrations.AddField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(default='2000-12-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='nss',
            field=models.CharField(default='2323', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='place_of_birth',
            field=models.CharField(default='D', max_length=50),
            preserve_default=False,
        ),
    ]
