# Generated by Django 5.1.4 on 2024-12-31 22:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_worker_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
