# Generated by Django 5.1.4 on 2024-12-31 22:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_appuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_user', max_length=255, verbose_name='image'),
        ),
    ]
