# Generated by Django 5.1.4 on 2024-12-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_appuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='image',
        ),
    ]
