# Generated by Django 5.1.4 on 2024-12-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DemandeCerteficat',
            new_name='DemandCertificate',
        ),
        migrations.RenameModel(
            old_name='DemandeFacture',
            new_name='DemandFacture',
        ),
    ]
