# Generated by Django 5.1.4 on 2024-12-27 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0002_rename_demandecerteficat_demandcertificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='consultation',
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pp.prescription'),
        ),
        migrations.AddField(
            model_name='demandfacture',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('priority', models.CharField(max_length=10)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.consultation')),
                ('labtechnician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('priority', models.CharField(max_length=10)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.consultation')),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.worker')),
            ],
        ),
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.bilanradiologique')),
            ],
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='compteRendu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pp.compterendu'),
        ),
        migrations.CreateModel(
            name='LabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bilan_images/')),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.bilanbiologique')),
            ],
        ),
        migrations.CreateModel(
            name='LabObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.bilanbiologique')),
            ],
        ),
        migrations.CreateModel(
            name='RadioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='radio_images/')),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('compteRendu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp.compterendu')),
            ],
        ),
    ]
