# Generated by Django 5.1.4 on 2024-12-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0003_remove_prescription_consultation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compterendu',
            name='bilan',
        ),
    ]
