# Generated by Django 5.1.4 on 2024-12-27 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0004_remove_compterendu_bilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consult', to='pp.consultation'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescript', to='pp.prescription'),
        ),
    ]
