# Generated by Django 5.1.4 on 2024-12-27 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp', '0005_prescription_consultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compterendu',
            name='bilan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pp.bilanradiologique'),
        ),
    ]
