# Generated by Django 5.1.4 on 2024-12-27 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('actions_taken', models.TextField(blank=True, null=True)),
                ('observations', models.TextField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
