# Generated by Django 5.1.4 on 2024-12-27 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('priority', models.CharField(max_length=10)),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker')),
            ],
        ),
        migrations.CreateModel(
            name='CompteRendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('bilan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.bilanradiologique')),
            ],
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='compteRendu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.compterendu'),
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.consultation'),
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('priority', models.CharField(max_length=10)),
                ('labtechnician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker')),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='LabImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bilan_images/')),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.bilanbiologique')),
            ],
        ),
        migrations.CreateModel(
            name='LabObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('bilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.bilanbiologique')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consult', to='doctor.consultation')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescript', to='doctor.prescription'),
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(through='doctor.PrescriptionDetail', to='doctor.medicine'),
        ),
        migrations.CreateModel(
            name='RadioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='radio_images/')),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('compteRendu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.compterendu')),
            ],
        ),
    ]
