# Generated by Django 5.1.4 on 2024-12-29 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_date_consultation_created_at'),
        ('users', '0003_remove_patient_date_of_birth_remove_patient_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labobservation',
            name='bilan',
        ),
        migrations.RemoveField(
            model_name='labimage',
            name='bilan',
        ),
        migrations.RemoveField(
            model_name='bilanradiologique',
            name='compteRendu',
        ),
        migrations.RemoveField(
            model_name='bilanradiologique',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='bilanradiologique',
            name='radiologist',
        ),
        migrations.RemoveField(
            model_name='compterendu',
            name='bilan',
        ),
        migrations.RemoveField(
            model_name='radioimage',
            name='compteRendu',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='summary',
            new_name='resume',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='labobservation',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='valid',
        ),
        migrations.RemoveField(
            model_name='radioimage',
            name='observation',
        ),
        migrations.AddField(
            model_name='consultation',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultation',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], default='Low', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='reason',
            field=models.CharField(default='Niggabite', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labobservation',
            name='notes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='labobservation',
            name='title',
            field=models.CharField(default='dee', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Failed', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labimage',
            name='image',
            field=models.ImageField(upload_to='Lab_images/'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.consultation'),
        ),
        migrations.AlterField(
            model_name='radioimage',
            name='image',
            field=models.ImageField(upload_to='Ladio_images/'),
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labtechnician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker')),
            ],
        ),
        migrations.AddField(
            model_name='labimage',
            name='labresult',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='doctor.labresult'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labobservation',
            name='labresult',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='doctor.labresult'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NursingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker')),
            ],
        ),
        migrations.CreateModel(
            name='NursingObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('nursingresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.nursingresult')),
            ],
        ),
        migrations.CreateModel(
            name='RadioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radiologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worker')),
            ],
        ),
        migrations.CreateModel(
            name='RadioObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
                ('radioresult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.radioresult')),
            ],
        ),
        migrations.AddField(
            model_name='radioimage',
            name='radioresult',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='doctor.radioresult'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Critical', 'Critical')], max_length=20)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.consultation')),
            ],
        ),
        migrations.AddField(
            model_name='radioresult',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.ticket'),
        ),
        migrations.AddField(
            model_name='nursingresult',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.ticket'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.ticket'),
        ),
        migrations.DeleteModel(
            name='BilanBiologique',
        ),
        migrations.DeleteModel(
            name='BilanRadiologique',
        ),
        migrations.DeleteModel(
            name='CompteRendu',
        ),
    ]
