# Generated by Django 5.1.4 on 2024-12-30 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_consultation_resume'),
        ('doctor', '0004_ticket_status'),
    ]

    operations = [
    ]
