# Generated by Django 5.1.4 on 2024-12-30 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_merge_20241230_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('Lab', 'Lab'), ('Radio', 'Radio'), ('Nursing', 'Nursing')], max_length=20),
        ),
    ]
