# Generated by Django 5.1.4 on 2024-12-31 22:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_ticket_created_at_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='radioimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
