# Generated by Django 5.1.4 on 2024-12-31 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_labimage_image_alter_radioimage_image'),
        ('users', '0005_alter_appuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.hospital'),
            preserve_default=False,
        ),
    ]
