# Generated by Django 5.1.4 on 2025-01-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_prescription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondetail',
            name='frequency',
            field=models.CharField(default='twice a day', max_length=50),
            preserve_default=False,
        ),
    ]
