# Generated by Django 5.1.4 on 2025-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_prescriptiondetail_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
